apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: back-end
          image: 073278647946.dkr.ecr.us-east-2.amazonaws.com/go-hello-app:1.0.8
          ports:
            - containerPort: 9090
