apiVersion: v1
kind: Service
metadata:
  name: hello-app-service
  annotations:
    jenkinsx.alpha.kubernetes.io/hostname: go-hello-app.jenkinsx.net
spec:
  type: LoadBalancer
  selector:
    app: web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9090
